name: 'publish'
on:
  push:
    branches:
      - 'main'

jobs:
  build-dev:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build YAMCL
        run: cargo tauri build -d
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
            name: builds-${{ runner.os }}
            path: |
              src-tauri/target/debug/bundle/**/*.AppImage
              src-tauri/target/debug/bundle/**/*.deb
              src-tauri/target/debug/bundle/**/*.exe
              src-tauri/target/debug/bundle/**/*.msi
              src-tauri/target/debug/bundle/**/*.dmg
